### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vvlladd28**

### CODE REVIEW

**Review by vvlladd28 — COMMENTED** [review]
55

**Review by vvlladd28 — COMMENTED** [review]
fdfd

**Review by vvlladd28 — COMMENTED** [review]
12

**Review by vvlladd28 — COMMENTED** [review]
1

**Comment by vvlladd28** [comment]
1

**Comment by vvlladd28** [comment]
1

**Review by vvlladd28 — COMMENTED** [review]
12

**Review by vvlladd28 — COMMENTED** [review]
1

**Review by ArtemDzhereleiko — CHANGES_REQUESTED** [review]
12

**Review by ArtemDzhereleiko — APPROVED** [review]

**Review by vvlladd28 — COMMENTED** [review]
1

**Review by ArtemDzhereleiko — APPROVED** [review]

**Review by ArtemDzhereleiko — APPROVED** [review]

**Review by ArtemDzhereleiko — APPROVED** [review]

**Review by ArtemDzhereleiko — APPROVED** [review]

**Review by ArtemDzhereleiko — APPROVED** [review]

**Review by ArtemDzhereleiko — APPROVED** [review]

**Review by ArtemDzhereleiko — APPROVED** [review]

**Review by ArtemDzhereleiko — CHANGES_REQUESTED** [review]
12

**Review by ArtemDzhereleiko — CHANGES_REQUESTED** [review]
11

**Review by ArtemDzhereleiko — CHANGES_REQUESTED** [review]
10

**Pull request merged**
